[build]
builder = "NIXPACKS"

[deploy]
rootDirectory = "backend"
startCommand = "./minimal-test.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3