[build]
builder = "NIXPACKS"

[deploy]
rootDirectory = "backend"
startCommand = "node test-server.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3