[build]
builder = "nixpacks"

[deploy]
rootDirectory = "backend"
startCommand = "yarn db:migrate && yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3