[phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[phases.install]
dependsOn = ["setup"]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
dependsOn = ["install"]
cmds = ["yarn build"]

[start]
cmd = "yarn start"