[phases.setup]
nixPkgs = ["nodejs_18", "yarn"]

[phases.install]
cmds = ["yarn install --frozen-lockfile --production=false"]

[phases.build]
cmds = ["yarn build", "npx medusa build --admin-only"]

[start]
cmd = "yarn start"