[phases.setup]
nixPkgs = ["nodejs-20_x", "yarn", "postgresql", "bash"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn build:all"]

[start]
cmd = "./start.sh"

[variables]
NODE_ENV = "production"