[phases.setup]
nixPkgs = ["nodejs-20_x", "yarn", "postgresql"]

[phases.install]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
cmds = ["yarn build:all"]

[start]
cmd = "yarn start"

[variables]
NODE_ENV = "production"