[phases.setup]
nixPkgs = ["nodejs-20_x", "yarn-1_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["yarn install --frozen-lockfile"]

[phases.build]
dependsOn = ["install"]
cmds = ["yarn build:all"]

[start]
cmd = "yarn db:migrate && yarn start"