[variables]
NODE_VERSION = "20"
YARN_VERSION = "1.22.22"

[phases.setup]
nixPkgs = ["nodejs", "yarn", "postgresql"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "yarn install --frozen-lockfile --prefer-offline"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "yarn build:all"
]

[start]
cmd = "yarn start"