[phases.setup]
nixPkgs = ["nodejs_20", "yarn-1_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["yarn install || npm install"]

[phases.build]
dependsOn = ["install"]
cmds = ["echo 'No build needed'"]

[start]
cmd = "node test-server.js"