[phases.setup]
nixPkgs = ["nodejs_20", "yarn-1_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["yarn install"]

[phases.build]
dependsOn = ["install"]
cmds = ["yarn build"]

[start]
cmd = "yarn db:migrate && yarn start"