[build]
builder = "nixpacks"

[deploy]
startCommand = "yarn start"
restartPolicyType = "always"
healthcheckPath = "/health"
healthcheckTimeout = 300

[nixpacks]
providers = ["node"]

[nixpacks.setup]
nixPkgs = ["nodejs_20", "yarn"]

[nixpacks.build]
cmds = ["yarn install --frozen-lockfile", "yarn build", "yarn db:migrate"]

[nixpacks.start]
cmd = "yarn start"