[build]
builder = "NIXPACKS"
buildCommand = "yarn install && yarn build"

[deploy]
startCommand = "yarn predeploy && yarn start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3