[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "yarn"]

[build.nixpacksPlan.phases.install]
cmds = ["yarn install"]

[build.nixpacksPlan.phases.build]
cmds = ["yarn build"]

[build.nixpacksPlan.variables]
NODE_ENV = "production"

[deploy]
startCommand = "./start-production.sh"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "$PORT"
HOST = "0.0.0.0"