[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "always"
healthcheckPath = "/health"
healthcheckTimeout = 300

[nixpacks]
providers = ["node"]

[nixpacks.setup]
nixPkgs = ["nodejs_20", "yarn"]

[nixpacks.build]
cmds = ["yarn install --frozen-lockfile", "yarn build"]

[nixpacks.start]
cmd = "yarn start"