[phases.setup]
nixPkgs = ["nodejs_20", "yarn", "postgresql"]

[phases.install]
cmds = ["yarn install"]

[phases.build]
cmds = ["npx medusa db:migrate && npx medusa exec ./src/scripts/create-admin.ts && yarn build"]

[start]
cmd = "yarn start"

[variables]
NODE_ENV = "production"
PORT = "9000"
RAILWAY_RUN_UID = "0"