services:
  - type: web
    name: indecisive-wear-backend
    runtime: node
    repo: https://github.com/YOUR_GITHUB_USERNAME/indecisive-wear-store
    rootDir: backend/medusa-backend
    buildCommand: ./render-build.sh
    startCommand: ./start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # Add manually in Render dashboard
      - key: REDIS_URL
        sync: false # Add manually in Render dashboard
      - key: JWT_SECRET
        generateValue: true
      - key: COOKIE_SECRET
        generateValue: true
      - key: STRIPE_API_KEY
        sync: false # Add manually in Render dashboard
      - key: STRIPE_WEBHOOK_SECRET
        sync: false # Add after deployment
      - key: SUPABASE_URL
        sync: false # Add manually in Render dashboard
      - key: SUPABASE_ANON_KEY
        sync: false # Add manually in Render dashboard
      - key: SUPABASE_SERVICE_KEY
        sync: false # Add manually in Render dashboard
      - key: SUPABASE_JWT_SECRET
        sync: false # Add manually in Render dashboard
      - key: STORE_CORS
        value: https://your-frontend-domain.com
      - key: ADMIN_CORS
        value: https://indecisive-wear-backend.onrender.com
      - key: AUTH_CORS
        value: https://your-frontend-domain.com,https://indecisive-wear-backend.onrender.com
      - key: PORT
        value: 9000
      - key: STORE_URL
        value: https://your-frontend-domain.com